version: "3.7"

networks:
  fenzapi-dev:
    driver: bridge

services:
  fenzapi:
    image: fenz-api:lastest
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    container_name: fenz-api
    build:
      context: .
      dockerfile: src/Api.Main/Dockerfile
    ports:
      - "3333:80"
    depends_on:
      - fenz_postgresql
    networks:
      - fenzapi-dev

  fenz_postgresql:
    image: postgres
    healthcheck:
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: "joker"
      POSTGRES_PASSWORD: "gotham"
      APP_DB_USER: docker   
      APP_DB_PASS: docker
      APP_DB_NAME: fenz_db_dev
    container_name: fenz_db
    ports:
      - "15432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d/
    networks:
      - fenzapi-dev

  fenz_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "joker@fenz.com"
      PGADMIN_DEFAULT_PASSWORD: "jokeradmin"
    container_name: fenz_pgadmin
    ports:
      - "16543:80"
    depends_on:
      - fenz_postgresql
    networks:
      - fenzapi-dev
